GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667 HTTP/1.1
Content-Type: application/json

{
  "date": "2023-12-01",
  "description": "test",
  "specialist": "Nipa oy",
  "type": "Hospital",
  "discharge": {
    "criteria": "something",
    "date": "2023-12-05"
  }
}